### ISSUE TITLE
GCP location services missing

### ISSUE THREAD

**Issue by bkw** [doitintl/cloud-catalog#48]
I could swear we had something for GCP Maps stuff, but I can't seem to find it.
A case for custom-services/gcp.json, I guess.

/CC @hrisp

**Comment by hrisp** [comment]
Tony also asked for this GetPSS: https://doitintl.zendesk.com/agent/tickets/142442

**Comment by haizaar** [comment]
yes, we did: 
https://doitintl.zendesk.com/agent/tickets/142442
https://doitintl.atlassian.net/browse/CMP-13672

**Comment by alexei-led** [comment]
dixed
