### ISSUE TITLE
azure/security-center has wrong name or should be deleted

### ISSUE THREAD

**Issue by bkw** [doitintl/cloud-catalog#6]
azure resource `azure/security-center` has name `Microsoft Defender for Cloud` (which is already correctly being used for id `azure/defender-for-cloud`. It should probably be named "Microsoft Security Center" instead.

https://github.com/doitintl/cloud-catalog/blob/master/data/azure.json#L3072-L3092

Upon closer observation, the Url https://azure.microsoft.com/en-us/services/security-center/ redirects to https://azure.microsoft.com/en-us/services/defender-for-cloud/#overview, so I guess that either Security Center has been renamed or deprecated.

**Comment by alexei-led** [comment]
all data is taken from the Azure Products page. Will be updated once MS decides to do so.
